---

- name: "fluentbit | templatize main configuration"
  template:
    src: "etc/td-agent-bit.conf.j2"
    dest: "/etc/td-agent-bit/td-agent-bit.conf"
    mode: 0644
  notify: "enable and start fluentbit service"

- name: "fluentbit | templatize additional configuration"
  template:
    src: "{{ extra_config.template }}"
    dest: "/etc/td-agent-bit/{{ extra_config.name }}"
    mode: 0644
  loop: "{{ fluentbit_additional_conf_files }}"
  loop_control:
    loop_var: extra_config
  when: fluentbit_additional_conf_files | length() > 0
  notify: "restart fluentbit service"
